- id: doi:10.1038/s41467-022-31373-6
  image: https://i.ibb.co/vkN9rcd/phaselock.png
- id: doi:10.1038/s42255-023-00962-0
  image: https://i.ibb.co/9csTm75/Zn.png
- id: doi:10.1210/clinem/dgac271
  image: https://i.ibb.co/9ZwVCRp/CAH.png
- id: doi:10.1038/s41419-021-04468-z
  image: https://i.ibb.co/9qQdpQy/apoptosis.png
- id: doi:https://doi.org/10.1002/anie.202109510
  image: https://i.ibb.co/SvwQyrz/Zndye.png
- id: doi:10.1007/s40484-020-0213-6
  image: https://i.ibb.co/3vW31zr/cellbow.png
